services:
  example-advanced:
    image: taverntesting.github.io/integration-test-containers:example-advanced
    ports:
      - 5000:5000
  example-cookies:
    image: taverntesting.github.io/integration-test-containers:example-cookies
    ports:
      - 5001:5000
  integration:
    image: taverntesting.github.io/integration-test-containers:integration
    ports:
      - 5003:5000
  example-components:
    image: taverntesting.github.io/integration-test-containers:example-components
    ports:
      - 5009:5000
#  example-simple:
#    image: taverntesting.github.io/integration-test-containers:example-simple
#  example-remember:
#    image: taverntesting.github.io/integration-test-containers:example-remember
#  example-hooks:
#    image: taverntesting.github.io/integration-test-containers:example-hooks
