[build-system]
requires = ["flit-core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Framework :: Pytest",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities",
    "Topic :: Software Development :: Testing",
    "License :: OSI Approved :: MIT License",
]

keywords = ["testing", "pytest"]

name = "tavern"
description = "Simple testing of RESTful APIs"
version = "2.0.0alpha11"

dependencies = [
    "PyYAML>=5.3.1,<7",
    "attrs>=20.3.0,<=21.4.0",
    "jmespath<1",
    "jsonschema~=3.2.0",
    "paho-mqtt>=1.3.1,<=1.5.1",
    "pyjwt>=2.4.0,<3",
    "pykwalify>=1.8.0,<2",
    "pytest>=6.2,<8",
    "python-box>4,<6",
    "requests>=2.22.0,<3",
    "stevedore~=3.3.0",
]

requires-python = ">=3.7"

[[project.authors]]
name = "Michael Boulton"

[project.license]
file = "LICENSE"

[project.readme]
file = "README.rst"
content-type = "text/x-rst"

[project.urls]
Home = "https://taverntesting.github.io/"
Documentation = "https://tavern.readthedocs.io/en/latest/"
Source = "https://github.com/taverntesting/tavern"

[project.optional-dependencies]
tests = [
    "Faker~=7.0.1",
    "allure-pytest",
    "black==22.3.0",
    "colorlog~=6.6.0",
    "flake8",
    "flask~=2.0.0",
    "isort~=5.10.1",
    "itsdangerous~=2.0.0",
    "mypy",
    "mypy-extensions",
    "pygments",
    "pylint",
    "pytest-cov",
]

dev = [
    "bump2version",
    "pre-commit",
    "pygments",
    "twine",
    "wheel",
    "py~=1.10.0",
    "tox",
    "pip-tools",
]

[project.scripts]

tavern-ci = "tavern.entry:main"

[project.entry-points.pytest11]

tavern = "tavern._core.pytest"

[project.entry-points.tavern_http]
requests = "tavern._plugins.rest.tavernhook:TavernRestPlugin"
[project.entry-points.tavern_mqtt]
paho-mqtt = "tavern._plugins.mqtt.tavernhook"

