apiVersion: skaffold/v2beta28
kind: Config

build:
  artifacts:
  - image: tavern-integration-server
    bazel:
      target: //tests/integration:server_image.tar
  - image: tavern-example-advanced-server
    bazel:
      target: //example/advanced:server_image.tar
  local:
    push: false
  tagPolicy:
    customTemplate:
      template: latest

deploy:
  docker:
    images:
    - tavern-integration-server
    - tavern-example-advanced-server

portForward:
- #address: 127.0.0.1
  localPort: 6000
  port: 5004
  resourceName: tavern-integration-server
  resourceType: container
- #address: 127.0.0.1
  localPort: 5006
  port: 5001
  resourceName: tavern-example-advanced-server
  resourceType: container
